### ISSUE TITLE
Strange behaviour with < and > symbols

### ISSUE THREAD

**Issue by LordMZTE** [Toqozz/wired-notify#11]
## Current behaviour
When the title of a notification contains `<`, then the body is displayed in the title.
For example, when sending a notification with this command `notify-send 'title <' 'body'` then the text `body` is displayed in both the title and body of the notification.

Also, the XML entities `&lt;` and `&gt;` are displayed as-is and aren't being converted. Other daemons (tested with dunst) do this, and some programs (tested with discord) send notifications with these XML entities, which also don't look right in wired.

## Expected behaviour
Notifications containing `<` in their title should be displayed normally.
XML entities like `&lt;` and `&gt;` should be displayed as `<` and `>`.

## Version information
- wired version: commit 043f2b2
- OS: arch linux

My wired config which I can use to reproduce this is available [here](https://github.com/LordMZTE/dotfiles/blob/master/.config/wired/wired.ron)

**Comment by Toqozz** [comment]
Thanks for the issue!

I've fixed these specific cases in master.

The body text appearing in the summary after the bracket is really weird, and nothing in my code should do that.  My guess is that it's an overflow in pango due to the unescaped bracket.

The frustrating thing about marking up with pango is that the rules for conversion seem almost totally arbitrary.  For example, pango will automatically convert &gt; and &lt; to their counterparts, but it won't convert &quot; -- you'll have to do this one yourself.  This kind of stuff means you have to write code that converts *both* ways.

Looking at dunst implementation, it seems like we've covered all the characters they process there now (<, >, ', ", &), but that still doesn't give me confidence that *everything* is going to work.  They actually seem to be missing &#39; and &#34; which is an alternative for ' and  " -- I think maybe Discord sends it.
