### ISSUE TITLE
Potentially incorrect timeout behavior

### ISSUE THREAD

**Issue by bcspragu** [Toqozz/wired-notify#131]
According to the [Desktop Notifications Specification](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html), `expire_timeout` is:

>  The timeout time in milliseconds since the display of the notification at which the notification should automatically close.
>
> If -1, the notification's expiration time is dependent on the notification server's settings, and may vary for the type of notification. If 0, never expire. 

But in [my calendar notification tool](https://git.sr.ht/~bsprague/dont-miss-it), I've set [the timeout to never expire](https://git.sr.ht/~bsprague/dont-miss-it/tree/main/item/notifier.go#L97) ([which does indeed have a value of `0`](https://github.com/esiqveland/notify/blob/120b9022f591d4c502516e691acec335960d406d/notification.go#L63)), and I noticed it was still getting the default `timeout` specified in my `wired.ron` config.

I believe that's happening in [this code here](https://github.com/Toqozz/wired-notify/blob/d65f227779061299842b4e1891954c4843ee2750/src/bus/dbus.rs#L455-L458), which should read `if timeout < 0 { ... }` instead, and `timeout == 0` should be handled specially.

If I've gotten that correct, I'm happy to attempt to take this on (with a few pointers of how to do it)

**Comment by Toqozz** [comment]
If I recall correctly, this was somewhat of a conscious decision at the time.  Many notifications set a timeout of 0 and I personally don't like it.  However, now that wired has a significant userbase it's probably better to make this optional, and do the correct thing by default.

If you'd like to contribute, I think the easiest way to implement this is to just add a special case to that if statement: when timeout is 0, use `f32::INFINITY` instead.  Normally I'd want to change the timeout to use an enum type rather than infinity, but it seems to make sense conceptually here -- the timeout is infinite.

**Comment by bcspragu** [comment]
Sounds good, done in #134. If we don't want to break existing users here, we can hide the new stuff behind a flag.

>  Many notifications set a timeout of 0 and I personally don't like it

I agree, and I think a solution (separate from this issue/PR) would be to allow configuring timeouts and other behavior (e.g. urgency) based on `criteria` in the same way that rendering is.
