### ISSUE TITLE
Firefox doesn't detect "action" feature - resulting in using it's own notification system rather than wired

### ISSUE THREAD

**Issue by MonAaraj** [Toqozz/wired-notify#24]
Essentially, I've been having this problem where ever since I switched to wired - Firefox notifications would be quite different from what I configured wired notifications to be to be. After further investigation with an acquaintance, it became clear that it was Firefox's own notification handler, which it used to override my choice of notification daemon for some reason. After even more investigation, it looked like Firefox didn't use wired because [wired "didn't advertise" being able to handle notification "actions"](https://github.com/mozilla/gecko-dev/blob/581d9b3815d363cd2a6ef53c1f92bf536a23b5a8/toolkit/system/gnome/nsAlertsIconListener.cpp#L321)

My question here would be how I'd tell it to, well, persuade Firefox that wired indeed does handle them, and also if this is intended behavior. Thank for taking your time.

**Comment by Toqozz** [comment]
That's puzzling, because Wired *does* specify the `actions` capability: https://github.com/Toqozz/wired-notify/blob/457c1ad760f9b6c1cdb828f74aaae623ed0aff41/src/bus/receiver.rs#L30

I don't personally use web notifications, but I just tested with [this](https://www.bennish.net/web-notifications.html) site in Firefox and Wired does show the notification correctly.  What version are you running?  I think action support was only properly added in 0.9.0, but Wired has always listed the capability anyway, so I don't know what's wrong there.

**Comment by MonAaraj** [comment]
I think I got it. It was because I didn't restart my firefox when I switched from dunst to wired, so rather than it just using wired since i i used it as my notification daemon, it just gave up on trying to figure it out when i killed dunst, and used it's own. That's kind of weird, but it got fixed. Thank you very much for helping!
