### ISSUE TITLE
What's the proper way to start wired?

### ISSUE THREAD

**Issue by 0323pin** [Toqozz/wired-notify#42]
Hi,
Not so much of an issue, more like a general question.
After packaging `wired-notify` for NetBSD yesterday, I'm taking it for a spin.

I've added `wired &` to my LeftWM start-up file and it's working as it should using the default `wired.ron` for now.
But, I wonder if this is the correct way to do it, since the following shows-up in `top`

![2021-12-20-scrot](https://user-images.githubusercontent.com/90570748/146742542-8664e918-9d60-4d52-8def-430a88e48e38.png)

As you can see there're several instances running, each using a chuck of RAM. Should I start it as I do with `picom`, _i.e._ using something like 

```
if [ -x "$(command -v picom)" ]; then
  picom --config $SCRIPTPATH/picom.conf &> /dev/null &
fi
```

Thanks!

**Comment by Toqozz** [comment]
The proper way to start it is with `wired &`, like you've done.  There are some community efforts for systemd services (#34) but I haven't really made them part of the program yet.

I'm slightly puzzled by your `top`, but can't look into it on my machine right now, will do tomorrow.

There are a few things though which could cause multiple processes like you see.  On Wired master we're polling `DBus` in a separate thread to sort of work around an issue (https://github.com/diwic/dbus-rs/issues/364), which explains one of them, and then there's the main thread and I believe Winit might spawn a new thread for each window as well.

In regards to ram usage, I should probably look into it.  I haven't been excessively careful with memory and there's a bit of duplication; in particular, the layout config is copied for each window: https://github.com/Toqozz/wired-notify/blob/89bcfa66ad4165369b648b53b2ff040d11a8162f/src/rendering/window.rs#L45-L48 which can be a few kb depending on config.  Still, this is nothing compared to the cost of spawning a window so I haven't been too concerned.

I am surprised to see `SIZE` be so large, but again this isn't actually *that* crazy because rust static links by default.  How big is your Wired executable?  Maybe we could look at replacing some dependencies...

**Comment by 0323pin** [comment]
Thank you for your reply.

> There are some community efforts for systemd services (#34)

As I'm on NetBSD, I don't really care about `systemd`, as long as it's an option and not a headache :)

> How big is your Wired executable?

`wired                     │ File    │                           │ 1         │ 1259381 │ false    │ rwxr-xr-x │ root │ wheel │  3,631,200`

Actually, I've found what's going on. If, I logout and login again, there's only one process running. But, a new gets added if I reload my WM configuration. This is what is happening now, as I'm slowly going through a few configuration changes and I'm reloading it to check the effect of these.

**Comment by 0323pin** [comment]
@Toqozz I don't know if you had the time to check memory usage on your system but, I'm closing this issue now as the issue with several running instances was just a side effect of WM restart.

Using `wired-notify` together with `citron` for on-demand notifications. Thanks for providing this daemon.
