### ISSUE TITLE
Progress block breaks notification body

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#50]
https://user-images.githubusercontent.com/842850/152883373-9ad44dd5-308c-4488-be77-0fe6c12c7530.mp4

After updating to `0.10.0`, rendering with a `ProgressBlock` breaks the notification rendering.

[config](https://gist.github.com/lukelex/ee0872b126a56e5dd115529c606627c4)

**Comment by Toqozz** [comment]
https://github.com/Toqozz/wired-notify/blob/86474199996549ca5e954c91f61136bee890309a/src/rendering/layout.rs#L177-L182

After some sleuthing, here's the (main) problem code.  `set_operator(Source)` outside of a `save()/restore()` combo carries on to the next draw call and then pollutes the whole thing.  I think `ProgressBlock` is the only block that relies on the default operator being `cairo::Operator::Over`, which is why it happens when that block is present, but I think I'll also make this a guarantee by setting it before drawing each block to avoid the implicit behavior.

Fixed in master, will push 0.10.1 soon.

![img-2022-02-08-165420](https://user-images.githubusercontent.com/6947819/152934759-5a26a145-6214-43ab-889b-78b77f051e31.png)

**Comment by Toqozz** [comment]
Fixed in `0.10.1`.
