### ISSUE TITLE
Mouse warping to notifications (i3)

### ISSUE THREAD

**Issue by lilithium-hydride** [Toqozz/wired-notify#7]
On i3 (and I'm assuming any other WM with mouse warping), notifications from wired will often steal the input focus from whatever other application currently has it, additionally causing the cursor to be instantly placed in the center of the notification. This is especially painful when the notification appears on a different monitor, moving your cursor and focus to the notification, and then the window below it once the notification disappears. Vim user? You just threw a *lot* of odd input at whatever buffer you currently have open. According to [this issue](https://github.com/i3/i3/issues/3507), it seems that wired is not setting the proper hints to tell the window manager how to properly handle the notification windows. The issue links to [this standards guide](https://tronche.com/gui/x/icccm/sec-4.html#s-4.1.7), where it *looks* like the correct hint to fix this is "Passive" input focus, but I have zero real knowledge in this area so I could be talking nonsense. I've also tried `no_focus [class="wired"]` as suggested in the thread, but this doesn't reliably fix anything, so it looks like it must be fixed on wired's side.

**Comment by Toqozz** [comment]
I'm almost certain this isn't a hint issue, or at least not in the way mentioned here.

Assuming Dunst doesn't have the same issue; here's the output for `xprop` on a `dunst` window:
```
_NET_WM_WINDOW_OPACITY(CARDINAL) = 4294967200
_NET_WM_STATE(ATOM) = _NET_WM_STATE_ABOVE
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_UTILITY
WM_CLASS(STRING) = "Dunst", "Dunst"
_NET_WM_NAME(UTF8_STRING) = "Dunst"
WM_NAME(STRING) = "Dunst"
```

And here's the output of `xprop` on a `wired` window:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 1 by 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_UTILITY, _NET_WM_WINDOW_TYPE_NOTIFICATION
WM_CLIENT_MACHINE(STRING) = "qhost"
_NET_WM_PID(CARDINAL) = 3156
WM_CLASS(STRING) = "wired", "wired"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "wired"
WM_NAME(STRING) = "wired"
```

There's more because we're using a generic library for opening windows ([winit](https://github.com/rust-windowing/winit)), but to my knowledge the main hints required for notification behavior are the `UTILITY` and `NOTIFICATION` ones: https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html.  I don't think i3 should be focusing the window if it has these hints present.

Anyway, I'm going to install i3 now and see if I can reproduce.

**Comment by Toqozz** [comment]
Ok, was able to reproduce and fix (at least with default config).

A few notes for documentation purposes;

I thought the culprit was i3 not focusing windows with `_NET_WM_STATE_ABOVE`, since that's the only property that I could see interfering, which lead me to [my own post](https://github.com/rust-windowing/winit/issues/1139) from 2019!

If that post is to be believed, it's actually a bug/unintended that `dunst` is able to set the `_NET_WM_STATE_ABOVE` property while `_NET_WM_WINDOW_TYPE_NOTIFICATION/UTILITY` is set, so *hopefully* no WMs are reading the `ABOVE` property while ignoring the window type props.

Luckily, i3 seems to actually just be reading the `override_redirect` attribute, and setting it fixes the behavior.  This probably should have been on already, but it does nothing on bspwm with the above properties set, so I didn't even know what it was even supposed to do.

`override_redirect` doesn't seem to show up in xprop:
```
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified size: 1 by 1
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_UTILITY
WM_CLIENT_MACHINE(STRING) = "qhost"
_NET_WM_PID(CARDINAL) = 140993
WM_CLASS(STRING) = "wired", "wired"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_NAME(UTF8_STRING) = "wired"
WM_NAME(STRING) = "wired"
```

I've fixed this in master.  I'll push a new release to AUR within the next week.

**Comment by lilithium-hydride** [comment]
Wow that was quick :D Much appreciated!
