### ISSUE TITLE
Conditionally set progress bar color?

### ISSUE THREAD

**Issue by GoldsteinE** [Toqozz/wired-notify#87]
Hi! My usecase is following: I want to display progress bar for volume and color it differently when volume is muted. Currently I could probably achieve this by creating two identical blocks with different `AppName`, but this is an unpleasant duplication.

**Comment by GoldsteinE** [comment]
Actually, two blocks with different `AppName` would not be deduplicated with tags, so I ended up matching on `Body` instead, which is even more of a hack (and for some reason not guaranteed?)

**Comment by Toqozz** [comment]
Why is it not guaranteed?

**Comment by GoldsteinE** [comment]
I’m not sure, but that’s what the documentation says:

> When the notification has some body text (not guaranteed).

**Comment by Toqozz** [comment]
Right, that's because it is not required for a notification to have body text, only summary text, e.g.: `notify-send "summary"`.  I'll edit that section to make it a bit clearer

I assume you're creating the notifications yourself, so the right way of handling this is probably to support supplying some extra data which you can then use with a `RenderCriteria`.  Maybe something like: `notify-send "Summary" "Body" --hint="string:wired-note:mute"`?

> but this is an unpleasant duplication.

Unfortunately I don't think we can do much better than this.  If we have options for specific use cases just under the Progress bar, then it balloons out exponentially.  It would be nice if we could have some kind of conditional inclusions or something, but we're just not set up for that right now.  Here's an issue that talks about some potential options: https://github.com/Toqozz/wired-notify/issues/81

**Comment by GoldsteinE** [comment]
I thought about `%`-syntax in `Color` strings.

> I assume you're creating the notifications yourself, so the right way of handling this is probably to support supplying some extra data which you can then use with a RenderCriteria. Maybe something like: notify-send "Summary" "Body" --hint="string:wired-note:mute"?

Yes, that would be a lot cleaner.

**Comment by Toqozz** [comment]
I've added `RenderCriteria::Note` in master.  You can use it like this:

In `wired.ron`:
```
render_criteria: [Note("mute")],
```

When sending the notification:
```
$ notify-send "Summary" "Body" --hint="string:wired-note:mute"
```

**Comment by GoldsteinE** [comment]
Thanks!
